# Project: UML Aloha
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o magazzino.o prodotto.o $(RES)
LINKOBJ  = main.o magazzino.o prodotto.o $(RES)
LIBS =  -L"D:/Personali Gianlorenzo/Documenti/Portable/dev_portable/Dev-CppPortable/App/devcpp/lib"  
INCS =  -I"D:/Personali Gianlorenzo/Documenti/Portable/dev_portable/Dev-CppPortable/App/devcpp/include" 
CXXINCS =  -I"D:/Personali Gianlorenzo/Documenti/Portable/dev_portable/Dev-CppPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"D:/Personali Gianlorenzo/Documenti/Portable/dev_portable/Dev-CppPortable/App/devcpp/include/c++/3.4.2/backward"  -I"D:/Personali Gianlorenzo/Documenti/Portable/dev_portable/Dev-CppPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"D:/Personali Gianlorenzo/Documenti/Portable/dev_portable/Dev-CppPortable/App/devcpp/include/c++/3.4.2"  -I"D:/Personali Gianlorenzo/Documenti/Portable/dev_portable/Dev-CppPortable/App/devcpp/include" 
BIN  = "UML Aloha.exe"
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before "UML Aloha.exe" all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "UML Aloha.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

magazzino.o: magazzino.cpp
	$(CPP) -c magazzino.cpp -o magazzino.o $(CXXFLAGS)

prodotto.o: prodotto.cpp
	$(CPP) -c prodotto.cpp -o prodotto.o $(CXXFLAGS)
